version: '3.8'
services:
  reverse_proxy:
    container_name: reverse_proxy
    hostname: reverse_proxy
    image: caddy:alpine
    volumes:
      - ./caddy/config:/config
      - ./caddy/data:/data
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./wp/data:/var/www/html/wp
      - ./mautic/data:/var/www/html
    networks:
      - mkt
      - reverse_proxy
    ports:
      - 80:80
      - 443:443
  mautic:
    container_name: mautic
    hostname: mautic
    image: mautic/mautic:v4-fpm
    # working_dir: /var/www/html/mautic
    env_file:
      - ./mautic/.env
    networks:
      - mkt
    volumes:
      - ./mautic/data:/var/www/html
  wordpress:
    container_name: wordpress
    hostname: wordpress
    image: wordpress:6.2-fpm
    working_dir: /var/www/html/wp
    env_file:
      - ./wp/.env
    networks:
      - mkt
    volumes:
      - ./wp/data:/var/www/html/wp
  sql:
    container_name: sql
    hostname: sql
    image: mariadb:10-jammy
    env_file:
      - ./sql/.env
    networks: 
    - mkt
    volumes:
      - ./sql/data:/var/lib/mysql
networks:
  mkt: {}
  reverse_proxy: {}
