
version: "3.8"
services:
  reverse_proxy:
    container_name: reverse_proxy
    hostname: reverse_proxy
    image: caddy:alpine
    volumes:
      - ./caddy/config:/config
      - ./caddy/data:/data
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./wp/data:/var/www/html/wp
    networks:
      - mkt
      - reverse_proxy
    ports:
      - 80:80
      - 443:443
  wordpress:
    container_name: wordpress
    hostname: wordpress
    image: wordpress:6.2-fpm
    working_dir: /var/www/html/wp
    env_file:
      - ./wp/.env
    networks:
      - mkt
    volumes:
      - ./wp/data:/var/www/html/wp
  sql:
    container_name: sql
    hostname: sql
    image: mariadb:10-jammy
    env_file:
      - ./sql/.env
    networks: 
    - mkt
    volumes:
      - ./sql/data:/var/lib/mysql
networks:
  mkt: {}
  reverse_proxy: {}

